import '../models/subscription_model.dart';
import 'subscription_icon_registry.dart';

final List<SubscriptionModel> dummySubscriptions = [
  SubscriptionModel(
    id: '1',
    name: 'Netflix',
    category: 'Entertainment',
    monthlyPrice: 15.99,
    yearlyPrice: 191.88,
    billingCycle: BillingCycle.monthly,
    startDate: DateTime.now().subtract(const Duration(days: 820)), // 2 years 3 months
    nextRenewalDate: DateTime.now().add(const Duration(days: 12)),
    status: SubscriptionStatus.active,
    iconUrl: SubscriptionIconRegistry.getIconUrl('netflix'),
    hasReminder: true,
  ),
  SubscriptionModel(
    id: '2',
    name: 'Spotify',
    category: 'Music',
    monthlyPrice: 10.99,
    yearlyPrice: 131.88,
    billingCycle: BillingCycle.monthly,
    startDate: DateTime.now().subtract(const Duration(days: 515)),
    nextRenewalDate: DateTime.now().add(const Duration(days: 3)),
    status: SubscriptionStatus.upcoming,
    iconUrl: SubscriptionIconRegistry.getIconUrl('spotify'),
  ),
  SubscriptionModel(
    id: '3',
    name: 'YouTube Premium',
    category: 'Entertainment',
    monthlyPrice: 13.99,
    yearlyPrice: 167.88,
    billingCycle: BillingCycle.monthly,
    startDate: DateTime.now().subtract(const Duration(days: 180)),
    nextRenewalDate: DateTime.now().add(const Duration(days: 20)),
    status: SubscriptionStatus.active,
    iconUrl: SubscriptionIconRegistry.getIconUrl('youtube_premium'),
  ),
  SubscriptionModel(
    id: '4',
    name: 'Amazon Prime',
    category: 'Shopping',
    monthlyPrice: 14.99,
    yearlyPrice: 139.00,
    billingCycle: BillingCycle.yearly,
    startDate: DateTime.now().subtract(const Duration(days: 1095)),
    nextRenewalDate: DateTime.now().add(const Duration(days: 150)),
    status: SubscriptionStatus.active,
    iconUrl: SubscriptionIconRegistry.getIconUrl('amazon_prime'),
  ),
  SubscriptionModel(
    id: '5',
    name: 'Google One',
    category: 'Cloud Storage',
    monthlyPrice: 1.99,
    yearlyPrice: 19.99,
    billingCycle: BillingCycle.yearly,
    startDate: DateTime.now().subtract(const Duration(days: 365)),
    nextRenewalDate: DateTime.now().subtract(const Duration(days: 5)),
    status: SubscriptionStatus.expired,
    iconUrl: SubscriptionIconRegistry.getIconUrl('google_one'),
  ),
  SubscriptionModel(
    id: '6',
    name: 'ChatGPT Plus',
    category: 'Productivity',
    monthlyPrice: 20.00,
    yearlyPrice: 240.00,
    billingCycle: BillingCycle.monthly,
    startDate: DateTime.now().subtract(const Duration(days: 240)),
    nextRenewalDate: DateTime.now().add(const Duration(days: 8)),
    status: SubscriptionStatus.active,
    iconUrl: SubscriptionIconRegistry.getIconUrl('chatgpt_plus'),
    hasReminder: true,
  ),
  SubscriptionModel(
    id: '7',
    name: 'Microsoft 365',
    category: 'Productivity',
    monthlyPrice: 6.99,
    yearlyPrice: 69.99,
    billingCycle: BillingCycle.yearly,
    startDate: DateTime.now().subtract(const Duration(days: 730)),
    nextRenewalDate: DateTime.now().add(const Duration(days: 45)),
    status: SubscriptionStatus.active,
    iconUrl: SubscriptionIconRegistry.getIconUrl('microsoft_365'),
  ),
  SubscriptionModel(
    id: '8',
    name: 'Adobe Creative Cloud',
    category: 'Design',
    monthlyPrice: 54.99,
    yearlyPrice: 659.88,
    billingCycle: BillingCycle.monthly,
    startDate: DateTime.now().subtract(const Duration(days: 30)),
    nextRenewalDate: DateTime.now().add(const Duration(days: 2)),
    status: SubscriptionStatus.upcoming,
    iconUrl: SubscriptionIconRegistry.getIconUrl('adobe_creative_cloud'),
  ),
];
