// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZQdydztpdjj7sy5l9aCAu1px5vKuyDN0',
    appId: '1:8756555168:web:3b383b34e6ac3b384c48c5',
    messagingSenderId: '8756555168',
    projectId: 'sanchora',
    authDomain: 'sanchora.firebaseapp.com',
    storageBucket: 'sanchora.firebasestorage.app',
    measurementId: 'G-WW51H90966',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP9tNcbyx2CIl_bFfZiD0crlYaVQ1Gx_Y',
    appId: '1:8756555168:android:a26608a25a0284cd4c48c5',
    messagingSenderId: '8756555168',
    projectId: 'sanchora',
    storageBucket: 'sanchora.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTwNg-kN2BOC8QQU3JFGVs8-C4XqqimpA',
    appId: '1:8756555168:ios:490512d8bb18328f4c48c5',
    messagingSenderId: '8756555168',
    projectId: 'sanchora',
    storageBucket: 'sanchora.firebasestorage.app',
    iosBundleId: 'com.example.sanchora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTwNg-kN2BOC8QQU3JFGVs8-C4XqqimpA',
    appId: '1:8756555168:ios:490512d8bb18328f4c48c5',
    messagingSenderId: '8756555168',
    projectId: 'sanchora',
    storageBucket: 'sanchora.firebasestorage.app',
    iosBundleId: 'com.example.sanchora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZQdydztpdjj7sy5l9aCAu1px5vKuyDN0',
    appId: '1:8756555168:web:12bc2a5d4ac7129a4c48c5',
    messagingSenderId: '8756555168',
    projectId: 'sanchora',
    authDomain: 'sanchora.firebaseapp.com',
    storageBucket: 'sanchora.firebasestorage.app',
    measurementId: 'G-VSE5CT8V6J',
  );
}
